import { readFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { AppPaths } from './app-paths';
import { paths } from './paths';
import type { AppConfig, AppPreferences, TenantBrand } from './schema';
import { secretKeyForApp } from './schema';
import { writeFileAtomic } from '../platform/atomic-write';

export async function loadConfig(path: string = paths.configFile): Promise<Partial<AppConfig>> {
  try {
    const text = await readFile(path, 'utf8');
    return JSON.parse(text) as Partial<AppConfig>;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {};
    throw err;
  }
}

/**
 * Atomic write: write to a sibling temp file with 0600 perms, then rename
 * (atomic on POSIX) into place. Avoids the partial-write window where a
 * crash could leave the config truncated, and keeps secret-bearing bytes
 * from ever existing at the final path with looser perms.
 */
/**
 * Build an AppConfig that points the app's secret at the encrypted local
 * keystore via an exec-provider SecretRef. Used by /account change and the
 * first-run migration path. Preserves the existing `preferences` block so
 * users don't lose unrelated settings on credential update.
 *
 * The provider command is a thin shell wrapper bridge writes under
 * `~/.lark-channel/secrets-getter` (always user-owned, never a symlink) so
 * lark-cli's AssertSecurePath audit accepts it regardless of how node was
 * installed (Homebrew / Volta / system pkg may put node behind a symlink
 * or root-own it). The wrapper internally `exec`s the real node + bridge
 * with `secrets get`. Bridge itself short-circuits the spawn and reads the
 * keystore directly when it sees its own wrapper path in `command`.
 */
export async function buildEncryptedAccountConfig(
  appId: string,
  tenant: TenantBrand,
  preferences?: AppPreferences,
  appPaths: Pick<AppPaths, 'secretsGetterScript'> & { rootDir?: string } = paths,
): Promise<AppConfig> {
  const wrapperPath = await ensureSecretsGetterWrapper(appPaths);
  return {
    accounts: {
      app: {
        id: appId,
        secret: {
          source: 'exec',
          provider: 'bridge',
          id: secretKeyForApp(appId),
        },
        tenant,
      },
    },
    secrets: {
      providers: {
        bridge: {
          source: 'exec',
          command: wrapperPath,
          // The wrapper has args baked in; pass none here.
          args: [],
        },
      },
    },
    ...(preferences ? { preferences } : {}),
  };
}

/**
 * Write (or rewrite) the secrets-getter wrapper to point at the currently-
 * running node + bridge entry script. Always rewrites — node path can move
 * between bridge runs (nvm version switch, re-install) and the wrapper
 * must stay in sync. Returns the wrapper path.
 *
 * File perms 0700 so audit's `world/group-writable` check passes (and
 * extra restrictive — wrapper is a private user resource).
 */
export async function ensureSecretsGetterWrapper(
  appPaths: Pick<AppPaths, 'secretsGetterScript'> & { rootDir?: string } = paths,
  opts: {
    platform?: NodeJS.Platform;
    nodePath?: string;
    bridgeEntry?: string;
  } = {},
): Promise<string> {
  const platform = opts.platform ?? process.platform;
  const wrapperPath =
    platform === 'win32' ? `${appPaths.secretsGetterScript}.cmd` : appPaths.secretsGetterScript;
  const node = opts.nodePath ?? process.execPath;
  const bridgeEntry = opts.bridgeEntry ?? process.argv[1] ?? '';
  const rootDir = appPaths.rootDir ?? dirname(appPaths.secretsGetterScript);

  if (platform === 'win32') {
    const dq = (s: string): string => `"${s.replace(/"/g, '""')}"`;
    const content =
      `@echo off\r\n` +
      `rem Auto-generated by lark-channel-bridge. Do not edit.\r\n` +
      `set "LARK_CHANNEL_HOME=${rootDir.replace(/"/g, '""')}"\r\n` +
      `${dq(node)} ${dq(bridgeEntry)} secrets get %*\r\n`;
    await writeFileAtomic(wrapperPath, content, { mode: 0o600 });
    return wrapperPath;
  }

  // Single-quoted shell-safe strings: escape any embedded single quotes.
  const sq = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`;
  const content =
    `#!/bin/sh\n` +
    `# Auto-generated by lark-channel-bridge. Do not edit.\n` +
    `# Forwards exec-provider requests to: node bridge secrets get\n` +
    `LARK_CHANNEL_HOME=${sq(rootDir)} exec ${sq(node)} ${sq(bridgeEntry)} secrets get "$@"\n`;

  await writeFileAtomic(wrapperPath, content, { mode: 0o700 });
  return wrapperPath;
}

export async function saveConfig(cfg: AppConfig, path: string = paths.configFile): Promise<void> {
  // chmod the temp file before rename, so the destination path is never
  // visible with default permissions.
  await writeFileAtomic(path, `${JSON.stringify(cfg, null, 2)}\n`, { mode: 0o600 });
}
